<a href="https://colab.research.google.com/github/ChennamaReddyRevanth/DEEP-LEARNING/blob/main/Apply_One_Hot_Encoding_for_categorical_Sequence_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [3]:
sequences=['cat and dog',
           'dog and bird',
           'bird in the sky',
           'fish in the ocean']


In [4]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(sequences)

In [5]:
#convert text sequences to integer sequences
integer_sequences= tokenizer.texts_to_sequences(sequences)

In [6]:
#pad sequences to a fixed length
max_len = max(map(len,integer_sequences))
padded_sequences = pad_sequences(integer_sequences,maxlen=max_len,padding='post')

In [8]:
#one-hot encode the padded sequences
one_hot_encoded=np.zeros((len(padded_sequences),max_len,len(tokenizer.word_index)+1),dtype=int)

In [9]:
for i,sequence in enumerate(padded_sequences):
  for j,index in enumerate(sequence):
    one_hot_encoded[i,j,index]=1
print("Original Sequences: ")
print(sequences)
print("\n One-Hot Encoded Sequences: ")
print(one_hot_encoded)

Original Sequences: 
['cat and dog', 'dog and bird', 'bird in the sky', 'fish in the ocean']

 One-Hot Encoded Sequences: 
[[[0 0 0 0 0 0 1 0 0 0]
  [0 1 0 0 0 0 0 0 0 0]
  [0 0 1 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0]]

 [[0 0 1 0 0 0 0 0 0 0]
  [0 1 0 0 0 0 0 0 0 0]
  [0 0 0 1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 1 0 0 0 0 0 0]
  [0 0 0 0 1 0 0 0 0 0]
  [0 0 0 0 0 1 0 0 0 0]
  [0 0 0 0 0 0 0 1 0 0]]

 [[0 0 0 0 0 0 0 0 1 0]
  [0 0 0 0 1 0 0 0 0 0]
  [0 0 0 0 0 1 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 1]]]
